### ISSUE TITLE
running sbt new eltimn/lift-mongo.g8 ERROR - undefined attribute description

### ISSUE THREAD

**Issue by guilhebl** [eltimn/lift-mongo.g8#10]
Trying to run using README instructions using 

`sbt new eltimn/lift-mongo.g8`

and getting:

src/main/g8/src/main/webapp/templates-hidden/base-wrap.html, context [anonymous] 6:39 internal error: org.stringtemplate.v4.compiler.STException: context [anonymous] 6:39 attribute description isn't defined
at giter8.G8$STErrorHandler.runTimeError(g8.scala:110)

Seems like an issue with `<meta name="description" content="$description$">`
after changing it to `<meta name="description" content="sample app">`
build went ok.

Scala - 2.12.2
SBT - 0.13.15
Java - 1.8.0_131
Linux Ubuntu 16.04

**Comment by eltimn** [comment]
I removed the description, so it should work now. Note that this still uses Lift 2.6. I'll hopefully have one for Lift 3 soon.
